import{initializeApp}from"https://www.gstatic.com/firebasejs/10.13.2/firebase-app.js";import{getMessaging,onMessage,isSupported,getToken,}from"https://www.gstatic.com/firebasejs/10.13.2/firebase-messaging.js";import{isSupported as isSwSupported}from"https://www.gstatic.com/firebasejs/10.13.2/firebase-messaging-sw.js";(async function(window){const MOBILE_APP_UUID='a6d37784-b931-4c30-b0a2-e7cb315be36d';var BASE_URL='https://indigoaviation-mkt-prod1-lb.campaign.adobe.com'
let ECID='';let serviceWorkerRegistration;let messaging;const util={getLang:()=>navigator.language,getOs:()=>navigator.platform,getBrowser:()=>{let ua=navigator.userAgent;let tem;let M=ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(M[1])){tem=/\brv[ :]+(\d+)/g.exec(ua)||[];return'IE '+(tem[1]||'');}
if(M[1]==='Chrome'){tem=ua.match(/\b(OPR|Edge)\/(\d+)/);if(tem!=null)return tem.slice(1).join(' ').replace('OPR','Opera');}
M=M[2]?[M[1],M[2]]:[navigator.appName,navigator.appVersion,'-?'];if((tem=ua.match(/version\/(\d+)/i))!=null)M.splice(1,1,tem[1]);return M.join(' ');},getUserKey:()=>getCookie("auth_user"),getEncKey:()=>window.msdv2.encryptionKey,getUserAgent:()=>navigator.userAgent,getMCID:()=>{console.log("getMCID:",ECID);return ECID;},getGAID:()=>{const match=document.cookie.match(/_ga=(.+?);/);return match?match[1].split('.').slice(-2).join('.'):'';},validateEmail:email=>{const re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(String(email).toLowerCase());},getDeviceDetails:()=>{const unknown='-';let screenSize='';if(screen.width)screenSize=`${screen.width} x ${screen.height}`;let nVer=navigator.appVersion;let nAgt=navigator.userAgent;let browser=navigator.appName;let version=''+parseFloat(navigator.appVersion);let majorVersion=parseInt(navigator.appVersion,10);let nameOffset,verOffset,ix;if((verOffset=nAgt.indexOf('Opera'))!=-1){browser='Opera';version=nAgt.substring(verOffset+6);if((verOffset=nAgt.indexOf('Version'))!=-1){version=nAgt.substring(verOffset+8);}}else if((verOffset=nAgt.indexOf('OPR'))!=-1){browser='Opera';version=nAgt.substring(verOffset+4);}else if((verOffset=nAgt.indexOf('Edge'))!=-1){browser='Microsoft Edge';version=nAgt.substring(verOffset+5);}else if((verOffset=nAgt.indexOf('MSIE'))!=-1){browser='Microsoft Internet Explorer';version=nAgt.substring(verOffset+5);}else if((verOffset=nAgt.indexOf('Chrome'))!=-1){browser='Chrome';version=nAgt.substring(verOffset+7);}else if((verOffset=nAgt.indexOf('Safari'))!=-1){browser='Safari';version=nAgt.substring(verOffset+7);if((verOffset=nAgt.indexOf('Version'))!=-1){version=nAgt.substring(verOffset+8);}}else if((verOffset=nAgt.indexOf('Firefox'))!=-1){browser='Firefox';version=nAgt.substring(verOffset+8);}else if(nAgt.indexOf('Trident/')!=-1){browser='Microsoft Internet Explorer';version=nAgt.substring(nAgt.indexOf('rv:')+3);}else if((nameOffset=nAgt.lastIndexOf(' ')+1)<(verOffset=nAgt.lastIndexOf('/'))){browser=nAgt.substring(nameOffset,verOffset);version=nAgt.substring(verOffset+1);if(browser.toLowerCase()==browser.toUpperCase()){browser=navigator.appName;}}
if((ix=version.indexOf(';'))!=-1)version=version.substring(0,ix);if((ix=version.indexOf(' '))!=-1)version=version.substring(0,ix);if((ix=version.indexOf(')'))!=-1)version=version.substring(0,ix);majorVersion=parseInt(''+version,10);if(isNaN(majorVersion)){version=''+parseFloat(navigator.appVersion);majorVersion=parseInt(navigator.appVersion,10);}
const mobile=/Mobile|mini|Fennec|Android|iP(ad|od|hone)/.test(nVer);let cookieEnabled=navigator.cookieEnabled;if(typeof navigator.cookieEnabled==='undefined'&&!cookieEnabled){document.cookie='testcookie';cookieEnabled=document.cookie.indexOf('testcookie')!==-1;}
const os=(()=>{const clientStrings=[{s:'Windows 10',r:/(Windows 10.0|Windows NT 10.0)/},{s:'Windows 8.1',r:/(Windows 8.1|Windows NT 6.3)/},{s:'Windows 8',r:/(Windows 8|Windows NT 6.2)/},{s:'Windows 7',r:/(Windows 7|Windows NT 6.1)/},{s:'Windows Vista',r:/Windows NT 6.0/},{s:'Windows XP',r:/(Windows NT 5.1|Windows XP)/},{s:'Windows 2000',r:/(Windows NT 5.0|Windows 2000)/},{s:'Android',r:/Android/},{s:'iOS',r:/(iPhone|iPad|iPod)/},{s:'Mac OS X',r:/Mac OS X/},{s:'Linux',r:/(Linux|X11)/},{s:'Unix',r:/UNIX/},];for(const client of clientStrings){if(client.r.test(nAgt))return client.s;}
return'unknown';})();return{screenSize,browser,version,os,mobile,cookieEnabled,};},};const registerServiceWorker=async()=>{try{const swOptions={type:"classic",scope:"/content/dam/s6web/generic-campaigns/webpush/script/",};const sw=await window.navigator.serviceWorker.register(`/content/dam/s6web/generic-campaigns/webpush/script/sw.js`,swOptions);return sw.update().then((registration)=>{console.log('==========> ',registration);console.log("SW Registered");return registration;}).catch((error)=>console.error("Can not update service worker",error));}catch(error){console.error("Can not register service worker",error);}};const requestPermission=async(messaging)=>{logMessage('Requesting permission...');try{const permission=await window.Notification.requestPermission();if(permission==="granted"){logMessage('Notification permission granted.');resetUI();}else{console.error("Unable to grant permission",permission);}}catch(error){console.error("Unable to request permission",error);}};const checkIfTokenIsNotGeneratedBefore=()=>!window.localStorage.getItem("fcm_token");if(!isSupported()){}else if(!isSwSupported()){}else if(window.Notification.permission==="denied"){console.log('==========> denied');}else{const firebaseConfig={apiKey:"AIzaSyA2DtNP74PW_YytMLOaJMmA4AlelnusHQc",projectId:"indigowebpushprod",messagingSenderId:"1096120976679",appId:"1:1096120976679:web:65829185af2857b41a9502"};const app=initializeApp(firebaseConfig,"indigo");messaging=getMessaging(app);serviceWorkerRegistration=await registerServiceWorker();getECID();resetUI();}
function processRequestPost(config){return new Promise(function(resolve,reject){try{fetch(config.url,{method:config.method,body:JSON.stringify(config.data),headers:{"Content-type":"application/json; charset=UTF-8"}}).then((response)=>response.json()).then((json)=>resolve(json));}catch(e){reject("Exception occured:"+e);}});}
function processRequest(config){return new Promise(function(resolve,reject){var xhr=new XMLHttpRequest();xhr.open(config.method,config.url);xhr.onload=function(){resolve(xhr.responseText)};xhr.onerror=function(){reject(xhr.statusText)};xhr.send();});}
function resetUI(){return getToken(messaging,{serviceWorkerRegistration,vapidKey:"BL0yO8olys5KNdqXXvncW3uB2vUmy3R5c_Rfg3Xtm1vsE6T2JAEdhx5aRhb30hh-0a7PA6rkn_afbWYRX2li5x8",}).then((currentToken)=>{if(currentToken){if(currentToken!=getFcmTokenSentToServer()){setTokenSentToServer(false);}
sendTokenToServer(currentToken);var devDetails=util.getDeviceDetails();var browserDetail=util.getBrowser();var browser=browserDetail.split(" ")[0];var browserVer=browserDetail.split(" ")[1];console.log("Browser Version: "+browserVer);}else{logMessage('Empty token returned from getToken.');setTokenSentToServer(false);}}).catch(function(err){console.log('An error occurred while retrieving token. ',err);setTokenSentToServer(false);});}
function logMessage(message){console.log(message);}
function getECID(){try
{ECID=_satellite.getVisitorId().getMarketingCloudVisitorID();}catch(e){console.log("getECID() Exception:",e);}}
function getCookie(cname){var name=cname+"=";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";}
function pollForDigitalData(currentToken){if(util.getMCID()=="")
{setTimeout(()=>{},1000);}
if(util.getUserKey()!==""){var devDetails=util.getDeviceDetails();sendClientToken(currentToken,util.getUserKey(),util.getMCID(),util.getGAID(),util.getLang(),devDetails.os,devDetails.osVersion,devDetails.browser,devDetails.browserVer,util.getUserAgent(),util.getEncKey());}else{var devDetails=util.getDeviceDetails();sendClientToken(currentToken,util.getUserKey(),util.getMCID(),util.getGAID(),util.getLang(),devDetails.os,devDetails.osVersion,devDetails.browser,devDetails.browserVer,util.getUserAgent(),util.getEncKey());}}
function sendTokenToServer(currentToken){if(!isTokenSentToServer()||(!isUserInfoSentToServer()&&(util.getUserKey()!==""&&util.getUserKey()!==null))){logMessage('Sending token to server...');pollForDigitalData(currentToken);}else{logMessage('Token already sent to server so won\'t send it again '+'unless it changes');}}
function getFcmTokenSentToServer(){return window.localStorage.getItem('fcm_token');}
function setFcmTokenSentToServer(currentToken){window.localStorage.setItem("fcm_token",currentToken);}
function isTokenSentToServer(){return window.localStorage.getItem('sentToServer')==1;}
function setTokenSentToServer(sent){window.localStorage.setItem('sentToServer',sent?1:0);}
function isUserInfoSentToServer(){return window.localStorage.getItem('sentUserInfoToServer')==1;}
function setUserInfoSentToServer(sent){window.localStorage.setItem('sentUserInfoToServer',sent?1:0);}
function sendClientToken(clientToken,userKey,mcid,gaid,language,os,osVer,browser,browserVer,ua,encKey){console.log(clientToken,userKey,mcid,gaid,language,os,osVer,browser,browserVer,ua);var data={"acui":MOBILE_APP_UUID,"ukey":userKey,"ctok":clientToken,"os":os,"osv":osVer,"osl":language,"manf":browser,"manfv":browserVer,"ecid":mcid,"encKey":encKey};var options={url:BASE_URL+'/acxwp/webregisterAndroid.jssp',method:'POST',data:data};processRequestPost(options).then(function(res){logMessage('Response is : '+JSON.stringify(res));setTokenSentToServer(true);if(util.getUserKey()!==""&&util.getUserKey()!==null){setUserInfoSentToServer(true);}
setFcmTokenSentToServer(clientToken);},function(err){logMessage('some error occurred --> '+JSON.stringify(err));});}})(window);